server:
  port: 8095

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pdd
    username: roo
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pdd.ordersync.entity
  configuration:
    map-underscore-to-camel-case: true

forest:
  max-connections: 1000        # 连接池最大连接数
  connect-timeout: 3000        # 连接超时时间，单位为毫秒
  read-timeout: 3000           # 数据读取超时时间，单位为毫秒




